name: whatthetest2
favicon: null
layout_spectrum: 0.69469
typography_spectrum: 0.31449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#475e12'
    - '#719a20'
    - '#b1bb85'
  brandStrength: 0.15650419960729778
  lightness: 0.8443512674421072
  saturation: 0.7615106429439038
  rhythmicContrast: 0.21860310132615268
purpose: []
