name: whatthetest2
favicon: null
layout_spectrum: 0.3096227429341525
typography_spectrum: 0.8138409988023341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15650419960729778
  lightness: 0.8443512674421072
  saturation: 0.7615106429439038
  rhythmicContrast: 0.21860310132615268
purpose: []
